### PR TITLE
server compress .js.gz if available

### PR DESCRIPTION
**Pull request by NakulManchanda**
Signed-off-by: Nakul Manchanda <nakul.manchanda@ibm.com>

Add ability if requested file is `app.min.js`
if `app.min.js.gz` is available, serve compressed and set appropriate content-encoding.

### CODE REVIEW

**Comment by NakulManchanda** [comment]
FYI @jordanCain

**Comment by NakulManchanda** [comment]
@jackjia-ibm some test were using 8080, some were using 9090
made it all 9090 - less chance of conflict

Added test to get file:
javascript1.min.js
javascript2.min.js => this returns  javascript2.min.js.gz

Unable to check content-encoding header, missing in our request library or when uncompressed its removed

Added relevant files as well


@jackjia-ibm can you check `npm run audit`, i think its been a while we updated this repo.

Thanks!

**Comment by NakulManchanda** [comment]
we need to test by running whole build with explorers especially JES explorer

JES Explorer build now produces app.min.js.gz file,
https://github.com/zowe/explorer-jes/pull/186

Also, need to verify in JES, if we are packaging app.min.js.gz or not

**Comment by NakulManchanda** [comment]
Build need to have following to verify this change:
explorer-ui-server - branch serve-compressed
explorer-jes - branch staging
rest default

**Comment by jackjia-ibm** [comment]
Including explorer-jes for integration test is over-complicated. The test related to this should be able to be self-contained. I found why the content-encoding header is not there because `axios` deleted it:

https://github.com/PaulAnnekov/axios/blob/master/lib/adapters/http.js#L194

I think to avoid this, we may need to switch away from axios. What do you think?

**Comment by NakulManchanda** [comment]
> Including explorer-jes for integration test is over-complicated. 

No not for integration test 
Just manual end-to-end testing as it has to serve explorers
image
**app.min.js - should be around 392KB, compared to 1.5MB now**

> I think to avoid this, we may need to switch away from axios. What do you think?
we can i can see if we can replace it with something else fetch/requests etc

**Comment by NakulManchanda** [comment]
its failing `npm audit`

one of the suggestion is:
```
# Run  npm install yargs@15.3.1  to resolve 1 vulnerability

SEMVER WARNING: Recommended action is a potentially breaking change
```

i believe yargs@15.3.1 is not compatible with node 6, but need to verify, thanks!
may be we need to find alternate, or can upgrade to some lower version

**Comment by NakulManchanda** [comment]
replaced `yargs` with `stdio`, its much **smaller package, pass audit**, used old version to be compatible with `node v6`, all test(s) are passing

**Comment by NakulManchanda** [comment]
@jackjia-ibm did major explore-ui server refactoring, its passing all tests.
just manual testing with explorers in custom build is left, 
all other checks are in.
Thanks!

**Comment by jackjia-ibm** [comment]
Those are a lot of changes, and many are way beyond the original purpose of this PR. One of my concern is the `process.stdout.write`. This was an issue that console log written into zowe log does not comply to the suggested message format. But seems the new changes are writing more logs and also not following the pattern. Since all these are already beyond this PR, not sure if you want to add one more utility function like `write_log` to use similar format like this:

```
2020-06-09 14:39:26.350 <ZWED:16843120> ZWESVUSR INFO (_zsf.bootstrap,plugin-loader.js:794) ZWED0124I - Plugin org.zowe.configjs at path=/ZOWE/staging/zowe/components/app-server/share/zlux-server-framework/plugins/config loaded.
```

Otherwise I think the zowe job log will look worse than before.

**Pull request merged**
